### ISSUE TITLE
關於x_1 題目資訊

### ISSUE THREAD

**Issue by DickLiu** [orderly-com/UbjAgkeP#1]
1. 請問一下題目中有敘明

> 設計出這 3 支手機的class

但是給的規格只有兩支手機 google phone / taiwan phone, 請問是否有遺漏呢? 謝謝

2. 手機二 taiwan phone的special_freature的規格, 在範例方面是否有更多的資訊補充呢?
我目前想到的疑問是如果Fibonacci計算的結果, 如果只有個位數的話, 例如Fibonacci(5)=5的話, 要回傳怎麼樣的數值呢, 能否再補充敘明? 謝謝

> 例如: ---

**Comment by kaijan** [comment]
1. 更正，2 支手機。

2. 這題同時也在展現思慮上的完整性，所以題目不提供更多的資訊～請把你想到的”可能”狀況都在程式裡處理
